GestionDeportiva/Controllers/AdministradoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using GestionDeportiva.Models;
using System.Threading;
using System.Data.Entity.Migrations;

namespace GestionDeportiva.Controllers
{
    public class AdministradoresController : Controller
    {
        private GestionEventosEntities db = new GestionEventosEntities();

        // GET: Administradores
        public async Task<ActionResult> Index()
        {
			var user = Session["UserProfile"];
            if (user != null)
            {
				return View(await db.Administradores.ToListAsync());

            }
            else
            {
                return RedirectToAction(nameof(Login));
            }
		}

        // GET: Administradores/Details/5
        public async Task<ActionResult> Details(int? id)
        {
			var user = Session["UserProfile"];
            if (user != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Administradores administradores = await db.Administradores.FindAsync(id);
                if (administradores == null)
                {
                    return HttpNotFound();
                }
                return View(administradores);
            }
            else
            {
                return RedirectToAction(nameof(Login));
            }
        }

        [HttpGet]
        public ActionResult ChangePassword(int? id)
        {
			var user = Session["UserProfile"];
            if (user != null)
            {
                var query = (from admin in db.Administradores
                             where admin.AdministradorId == id
                             select new { admin.NombreUsuario, admin.HashContrasena }).FirstOrDefault();
                LoginModel model = new LoginModel()
                {
                    LoginUser = query.NombreUsuario,
                    LoginPassword = ""
                };
                return View(model);
            }
            else
            {
				return RedirectToAction(nameof(Login));
			}
        }

        [HttpPost]
        public async Task<ActionResult> ChangePassword([Bind(Include = "LoginUser,LoginPassword")] LoginModel login)
		{
            try
            {
                var HashPassword = GetMD5Hash(login.LoginPassword);
                var user =await GetAdministradoresAsync(login.LoginUser);
                if(user != null)
                {
                    user.HashContrasena = HashPassword;
                }
                else
                {
                    throw new Exception("Error interno... Intentelo de nuevo");
                }
                db.Administradores.AddOrUpdate(user);
                db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }catch(Exception f)
            {
                ViewBag.ErrorMessage = f.Message;
				return View();
			}
            
        }
		private async Task<Administradores> GetAdministradoresAsync(string userName)
        {
            try
            {                
                var user = await ((from admin in db.Administradores
                        where admin.NombreUsuario.ToUpper() == userName.ToUpper()
                        select admin).FirstOrDefaultAsync());
                return user;                
            }catch(Exception v)
            {
                Console.WriteLine(v.Message);
                return null;
            }

		}
		private async Task<Administradores> GetAdministradoresAsync(int id)
        {
            throw new NotImplementedException();
        }

		// GET: Administradores/Create
		public ActionResult Create()
        {
			var user = Session["UserProfile"];
            if (user != null)
            {
				return View();
            }
            else
            {
                return RedirectToAction(nameof(Login));
            }			
        }

        // POST: Administradores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "AdministradorId,NombreUsuario,Nombre,Apellidos,HashContrasena")] Administradores administradores)
        {
			var user = Session["UserProfile"];
            if(user!= null)
            {
				if (ModelState.IsValid)
				{
					administradores.HashContrasena = GetMD5Hash(administradores.HashContrasena);
					db.Administradores.Add(administradores);
					await db.SaveChangesAsync();
					return RedirectToAction("Index");
				}
				return View(administradores);
            }
            else
            {
                return RedirectToAction(nameof(Login));
            }
        }

        // GET: Administradores/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
			var user = Session["UserProfile"];
            if (user != null)
            {
				if (id == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}
				Administradores administradores = await db.Administradores.FindAsync(id);
				if (administradores == null)
				{
					return HttpNotFound();
				}
				return View(administradores);
			}
            else
            {
                return RedirectToAction(nameof(Login));
            }

        }

        // POST: Administradores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "AdministradorId,NombreUsuario,Nombre,Apellidos,HashContrasena")] Administradores administradores)
        {
			var user = Session["UserProfile"];
            if (user != null)
            {
				if (ModelState.IsValid)
				{
					db.Entry(administradores).State = EntityState.Modified;
					await db.SaveChangesAsync();
					return RedirectToAction("Index");
				}
				return View(administradores);
			}
            else
            {
                return RedirectToAction(nameof(Login));
            }			
        }

        // GET: Administradores/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            var user = Session["UserProfile"];
            if (user != null)
            {
				if (id == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}
				Administradores administradores = await db.Administradores.FindAsync(id);
				if (administradores == null)
				{
					return HttpNotFound();
				}
				return View(administradores);
			}
            else
            {
                return RedirectToAction(nameof(Login));
            }

        }

        // POST: Administradores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
			var user = Session["UserProfile"];
            if (user != null)
            {
                Administradores administradores = await db.Administradores.FindAsync(id);
                db.Administradores.Remove(administradores);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction(nameof(Login));
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpGet]
		public async Task<ActionResult> Login()
		{
			var user = Session["UserProfile"];
			if (user == null)
            {
				return View();
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }				
		}
        [HttpPost]
		public async Task<ActionResult> Login([Bind(Include = "LoginUser,LoginPassword")] LoginModel login)
        {
            try
            {
                login.LoginPassword = GetMD5Hash(login.LoginPassword);
                // Logica de validación
                bool LoginSucess = validateLogin(login.LoginUser, login.LoginPassword, out int idUsuario);
                if (LoginSucess)
                {
                    Administradores UserActive = GetAdministradores(idUsuario);
                    Session["UserProfile"] = UserActive;
                    Session.Timeout = 2;
                    Session["UserName"] = UserActive.Nombre;
					return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.ErrorMessage = "Inicio de Sesión invalido\nRevise el nombre de usuario y contraseña";
					return View();
                }
                return View();
            }catch(Exception f)
            {
                ViewBag.ErrorMessage = f.Message;
				return View();
			}            
        }        

        public async Task<ActionResult> CloseSession()
        {
            Session["UserProfile"] = null;
            Session.Abandon();
			return RedirectToAction("Index", "Eventos");
        }
		private String GetMD5Hash(String input)
		{
			MD5CryptoServiceProvider x = new MD5CryptoServiceProvider();
			byte[] bs = System.Text.Encoding.UTF8.GetBytes(input);
			bs = x.ComputeHash(bs);
			System.Text.StringBuilder s = new System.Text.StringBuilder();
			foreach (byte b in bs)
			{
				s.Append(b.ToString("x2").ToLower());
			}
			String hash = s.ToString();
			return hash;
		}

GestionDeportiva/Controllers/TiposEventosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionDeportiva.Models;

namespace GestionDeportiva.Controllers
{
    public class TiposEventosController : Controller
    {
        private GestionEventosEntities db = new GestionEventosEntities();

        // GET: TiposEventos
        public async Task<ActionResult> Index()
        {
            return View(await db.TiposEventos.ToListAsync());
        }

        // GET: TiposEventos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TiposEventos tiposEventos = await db.TiposEventos.FindAsync(id);
            
            if (tiposEventos == null)
            {
                return HttpNotFound();
            }
            var data = (from evento in db.Eventos where evento.TipoEventoId == tiposEventos.TipoEventoId select evento).ToList();
            ViewBag.Eventos = data;
			return View(tiposEventos);
        }

        // GET: TiposEventos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TiposEventos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "TipoEventoId,Nombre")] TiposEventos tiposEventos)
        {
            if (ModelState.IsValid)
            {
                db.TiposEventos.Add(tiposEventos);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(tiposEventos);
        }

        // GET: TiposEventos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TiposEventos tiposEventos = await db.TiposEventos.FindAsync(id);
            if (tiposEventos == null)
            {
                return HttpNotFound();
            }
            return View(tiposEventos);
        }

        // POST: TiposEventos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "TipoEventoId,Nombre")] TiposEventos tiposEventos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tiposEventos).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(tiposEventos);
        }

        // GET: TiposEventos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TiposEventos tiposEventos = await db.TiposEventos.FindAsync(id);
            if (tiposEventos == null)
            {
                return HttpNotFound();
            }
            return View(tiposEventos);
        }

        // POST: TiposEventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            TiposEventos tiposEventos = await db.TiposEventos.FindAsync(id);
            db.TiposEventos.Remove(tiposEventos);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionDeportiva/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Eventos</title>
    <script src="~/Content/Site.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery-3.6.4.min.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="p-1">    
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary rounded rounded-1">
            <a class="navbar-brand" href="#">@Html.ActionLink("Eventos", "Index", "Eventos", null, new { @class = "nav-link text-light" })</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between " id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Tipos Eventos", "Index", "TiposEventos", null, new { @class = "nav-link text-light" })</li>
                    <li class="nav-item">@Html.ActionLink("Login", "Login", "Administradores", null, new { @class = "nav-link text-light" })</li>
                </ul>
                @using (Html.BeginForm("Search", "Eventos", FormMethod.Post, new { @class = "d-flex form-inline gap-1 m-1" }))
                {
                    <input name="EventoNombre" class="form-control mr-sm-2" type="search" placeholder="Evento" aria-label="Search">
                    <button class="btn btn-outline-success bg-light my-2 my-sm-0" type="submit">Search</button>
                }
            </div>
        </nav>        
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GestionDeportiva/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modo Admin - @ViewBag.Title </title>

    <script src="~/Content/Site.js"></script>
    <script src="~/Scripts/jquery-3.6.4.js"></script>
    <script src="~/Scripts/jquery-3.6.4.min.js"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/bootstrap")

    <script type="text/javascript" src="~/Scripts/umd/popper.js"></script>
    <script type="text/javascript" src="~/Scripts/umd/popper.min.js"></script>

    <script type="text/javascript" src="~/Scripts/popper-utils.js"></script>
    <script type="text/javascript" src="~/Scripts/popper-utils.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>

    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="p-1">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary rounded rounded-1">
        <a class="navbar-brand" href="#">@Html.ActionLink("Eventos", "Index", "Eventos", null, new { @class = "nav-link text-light" })</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between p-2 " id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">@Html.ActionLink("Tipos Eventos", "Index", "TiposEventos", null, new { @class = "nav-link text-light" })</li>
                <li class="nav-item">@Html.ActionLink("Administradores", "Index", "Administradores", null, new { @class = "nav-link text-light" })</li>
            </ul>
            <div class="d-inline-flex justify-content-center align-content-center m-1">
                @{
                    var user = (GestionDeportiva.Models.Administradores)Session["UserProfile"];
                    if (user != null)
                    {
                        <div class="d-inline-flex flex-row gap-1 text-light">
                            <label>
                                Hola @user.Nombre
                            </label>
                            <label>
                                |
                            </label>
                            @Html.ActionLink("Salir", "CloseSession", "Administradores", null, new { @class = "nav-link" })
                        </div>
                    }
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                Página de Administradores - @DateTime.Today.Year.ToString()
            </p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>


</html>