GestionDeportiva/Models/Eventos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeportiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int EventoId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Lugar { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> TipoEventoId { get; set; }
    
        public virtual TiposEventos TiposEventos { get; set; }
    }
}

GestionDeportiva/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionDeportiva.Models;
using System.IO;
using System.Drawing;
using System.Security.Cryptography;
using System.Data.Entity.Migrations;

namespace GestionDeportiva.Controllers
{
    public class EventosController : Controller
    {
        private GestionEventosEntities db = new GestionEventosEntities();

        // GET: Eventos
        public async Task<ActionResult> Index()
        {
            var eventos = db.Eventos.Include(e => e.TiposEventos).OrderByDescending(e => e.Fecha);           
            return View(await eventos.ToListAsync());
        }

        public async Task<ActionResult> Search( [Bind(Include = "EventoNombre")] string EventoNombre )
        {
            ViewBag.ValorBuscado = EventoNombre;
            List<Eventos> eventos = new List<Eventos>();
            eventos = (from evento in db.Eventos
                           where evento.Nombre.Contains(EventoNombre) || evento.Descripcion.Contains(EventoNombre)
                           select evento).ToList();
            return View(eventos);
        }


        // GET: Eventos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eventos eventos = await db.Eventos.FindAsync(id);
            if (eventos == null)
            {
                return HttpNotFound();
            }
            return View(eventos);
        }

        // GET: Eventos/Create
        public ActionResult Create()
        {
			var user = Session["UserProfile"];
            if (user != null)
            {
                ViewBag.TipoEventoId = new SelectList(db.TiposEventos, "TipoEventoId", "Nombre");
                return View();
            }
            else
            {
                return RedirectToAction(nameof(AdministradoresController.Login),"Administradores");
            }
        }

        // POST: Eventos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "EventoId,Nombre,Descripcion,Fecha,Lugar,TipoEventoId")] Eventos eventos)
        {
			var user = Session["UserProfile"];
            if (user != null)
            {

                if (ModelState.IsValid)
                {
                    if (Request.FilePath[0] != null)
                    {
                        /*
                         recibe la imagen en Request.Files 
                         */
                        var file = Request.Files[0];
                        // Convierte el archivo recibido en un Byte[] para luego asignarlo al Objeto de tipo Evento (el cual se almacenará en la base de datos)
                        MemoryStream target = new MemoryStream();
                        file.InputStream.CopyTo(target);
                        eventos.Imagen = target.ToArray();
                    }
                    db.Eventos.Add(eventos);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }

                ViewBag.TipoEventoId = new SelectList(db.TiposEventos, "TipoEventoId", "Nombre", eventos.TipoEventoId);
                return View(eventos);
            }
            else
            {
				return RedirectToAction(nameof(AdministradoresController.Login), "Administradores");
			}
        }

        // GET: Eventos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eventos eventos = await db.Eventos.FindAsync(id);
            if (eventos == null)
            {
                return HttpNotFound();
            }
			ViewBag.ErrorMessage = "";
			ViewBag.TipoEventoId = new SelectList(db.TiposEventos, "TipoEventoId", "Nombre", eventos.TipoEventoId);
            return View(eventos);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "EventoId,Nombre,Descripcion,Fecha,Lugar,TipoEventoId")] Eventos eventos)
        {
			var user = Session["UserProfile"];
			if (user != null)
            {
				if (ModelState.IsValid)
				{
                    var data = Request.Files;
					if (Request.FilePath[0] != null)
					{
						var file = Request.Files[0];
						MemoryStream target = new MemoryStream();
                        if (string.IsNullOrEmpty(file.FileName))
                        {
							var evento = await GetEventoAsync(eventos.EventoId);
							eventos.Imagen = evento.Imagen;
						}
                        else
                        {
							file.InputStream.CopyTo(target);
							eventos.Imagen = target.ToArray();
						}					
					}          
                    if( eventos.Fecha == null)
                    {
						var evento = await GetEventoAsync(eventos.EventoId);
                        eventos.Fecha = evento.Fecha;
					}
					using (db)
                    {
                        db.Eventos.AddOrUpdate(eventos);
                        db.SaveChanges();
                    }
					return RedirectToAction(nameof(Details), new { id= eventos.EventoId});
				}
				ViewBag.ErrorMessage = "";
				ViewBag.TipoEventoId = new SelectList(db.TiposEventos, "TipoEventoId", "Nombre", eventos.TipoEventoId);
				return View(eventos);
			}
            else
            {
                return RedirectToAction(nameof(AdministradoresController.Login), "Administradores");
            }			
        }

        // GET: Eventos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eventos eventos = await db.Eventos.FindAsync(id);
            if (eventos == null)
            {
                return HttpNotFound();
            }
            return View(eventos);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Eventos eventos = await db.Eventos.FindAsync(id);
            db.Eventos.Remove(eventos);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        private Task<Eventos> GetEventoAsync(int id)
        {
            try
            {
                var data = db.Eventos.Where(E => E.EventoId == id).FirstOrDefaultAsync();
                return data;
            }catch(Exception f)
            {
                Console.WriteLine(f.Message);
                return null;
            }
        }
    }
}

GestionDeportiva/Views/Eventos/Create.cshtml
@model GestionDeportiva.Models.Eventos

@{
    ViewBag.Title = "Crear Evento";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Crear Evento</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formPostEvento", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="container">
        <div class="row ">

            <div class="col-md-6">
                <!------------------>
                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>
                <!------------------>
                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @type = "textarea" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>
                <!------------------>
                <div class="form-group">
                    @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
                        @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

            <div class="col-md-6">

                <!------------------>
                <div class="form-group">
                    @Html.LabelFor(model => model.Lugar, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Lugar, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Lugar, "", new { @class = "text-danger" })
                    </div>
                </div>
                <!------------------>
                <div class="form-group">
                    @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <!-- Control para inserción de fotos, permite añadirle fotos a la pagina web. estas se enviaran mediante el modelo-->
                        @Html.TextBoxFor(model => model.Imagen, new { type = "file", accept = "image/*" })
                        @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                    </div>
                </div>
                <!------------------>
                <div class="form-group">
                    @Html.LabelFor(model => model.TipoEventoId, "TipoEventoId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TipoEventoId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TipoEventoId, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

        </div>
    </div>

    <div class="d-flex justify-content-center flex-row m-2">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-outline-primary" />
        </div>
        <div>
            @Html.ActionLink("Volver a la lista", "Index", null, new { @class = "btn btn-outline-info" })
        </div>
    </div>
}



<script>
    $("#formPostEvento").submit(function (e) {
        // e.preventDefault();
        console.log(e);
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionDeportiva/Views/Eventos/Delete.cshtml
@model GestionDeportiva.Models.Eventos

@{
    ViewBag.Title = "Borrar Elemento";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<h3>Esta seguro que sea eliminar este elemento?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lugar)
        </dd>   

        <dt>
            @Html.DisplayNameFor(model => model.TiposEventos.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TiposEventos.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-outline-danger" /> |
            @Html.ActionLink("Volver Atrás", "Index",null,new { @class="btn btn-outline-info"})
        </div>
    }
</div>

GestionDeportiva/Views/Eventos/Details.cshtml
@model GestionDeportiva.Models.Eventos

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex flex-column">
    <div class="d-flex justify-content-center">
        <h2>Detalles del Evento  @Model.Nombre</h2>
    </div>
</div>
<div class="container border-1 border-opacity-50 border-secondary rounded-1 rounded bg-primary bg-opacity-50 p-2">
    <div class="row">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <img src="@($"Data:image/PNG;base64,{Convert.ToBase64String(Model.Imagen)}")" class="d-block w-100 h-100 rounded rounded-1" alt="Imagen Evento" />
                </div>
                <div class="col-md-4 rounded rounded-1 text-light">
                    <h4>
                        Descripción
                    </h4>
                    <p>
                        @Model.Descripcion
                    </p>
                    <hr />
                    <h4>
                        Fecha del evento
                    </h4>
                    <p>
                        @Model.Fecha.Value.ToLongDateString() a las @Model.Fecha.Value.ToLongTimeString()
                    </p>
                    <hr />
                    <h4>
                        Lugar
                    </h4>
                    <p>
                        @Model.Lugar
                    </p>
                    <hr />
                    <h4>
                        Tipo
                    </h4>
                    <p>
                        @Model.TiposEventos.Nombre
                    </p>
                </div>
            </div>
        </div>      
    </div>
</div>


<div class="d-flex gap-2 m-1 justify-content-center">
    @if (Session["UserProfile"] != null)
    {
        @Html.ActionLink("Editar", "Edit", new { id = Model.EventoId }, new { @class = "btn btn-outline-success" })
        @Html.ActionLink("Eliminar", "Delete", new { id = Model.EventoId }, new { @class = "btn btn-outline-danger" })
    }
    @Html.ActionLink("Volver Atrás", "Index", null, new { @class = "btn btn-outline-info" })
</div>

GestionDeportiva/Views/Eventos/Edit.cshtml
@model GestionDeportiva.Models.Eventos

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex flex-column m-2">
    <div class="d-flex justify-content-center">
        <h2>Evento a Editar  @Model.Nombre</h2>
    </div>
</div>
<div class="container border-1 border-opacity-50 border-secondary rounded-1 rounded p-2">
    <div class="row">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <img src="@($"Data:image/PNG;base64,{Convert.ToBase64String(Model.Imagen)}")" class="d-block w-100 h-100" alt="..." />
                </div>
                <div class="col-md-4 rounded rounded-1">
                    @using (Html.BeginForm("Edit","Eventos",FormMethod.Post, new { id = "formPostEvento", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Eventos</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.EventoId)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local", @value= Model.Fecha.Value } })
                                    @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Lugar, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Lugar, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Lugar, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Imagen, new { type = "file", accept = "image/*" })
                                    @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.TipoEventoId, "TipoEventoId", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("TipoEventoId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.TipoEventoId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                                <label class="text-danger">@ViewBag.ErrorMessage</label>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>      
    </div>
</div>


<div>
    @Html.ActionLink("Volver Atrás", "Index",null,new { @class="btn btn-outline-info"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionDeportiva/Views/Eventos/Index.cshtml
@using System.Drawing;
@model IEnumerable<GestionDeportiva.Models.Eventos>


@{
    ViewBag.Title = "Eventos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Session["UserProfile"] != null)
{
    <div class="d-flex m-1">
        <p>
            @Html.ActionLink("Crear Evento", "Create", "Eventos", new { @class = "btn btn-outline-success" })
        </p>
    </div>
    <hr/>
}

<div id="carouselExampleCaptions" class="carousel slide m-2 data-bs-ride="carousel">
    <div class="carousel-inner">
        @{bool firts = false; }
        @foreach (var item in Model)
        {
            <div class="carousel-item active" data-bs-interval="2000">
                <!--
                    Explicación src= ($"Data:image/PNG;base64,{Convert.ToBase64String(item.Imagen)}")
                    el {Convert.ToBase64String(item.Imagen) convierte el Byte[] que viene desde la DB y lo convierte en un Base64 interpretable por el navegador
                -->
                <img src="@($"Data:image/PNG;base64,{Convert.ToBase64String(item.Imagen)}")" class=" img-fluid object-fit-cover  rounded rounded-1 d-block w-100" alt="..." style="height:45rem">
                <div class="carousel-caption d-none d-md-block bg-dark opacity-75 rounded-2">
                    <h5>@item.Nombre</h5>
                    <p>@item.Descripcion</p>
                    <p>@item.Fecha.Value.ToLongDateString()</p>
                </div>
            </div>
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<hr />

<div class="d-flex flex-md-wrap flex-column bg-opacity-50 m-2 rounded rounded-1" style="background-color:lightgray">
    <div class="d-flex flex-column align-items-center justify-content-center">
        <h2>Tabla de Eventos</h2>
        <h3>
            Lista de Eventos Diponibles
        <h3/>
    </div>
    <div class="d-flex gap-3 p-3 flex-wrap justify-content-center">
        @foreach (var item in Model)
        {
            <div class="card m-1" style="width: 18rem;">
                <img src="@($"Data:image/PNG;base64,{Convert.ToBase64String(item.Imagen)}")" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@item.Nombre</h5>
                    <p class="card-text">@item.Descripcion.</p>
                    <p class="card-text">Fecha: @item.Fecha.Value.ToLongDateString() - @item.Fecha.Value.ToShortTimeString();</p>
                    @Html.ActionLink("Ver información", "Details", new { id = item.EventoId }, new { @class = "btn btn-sm btn-outline-primary" })
                </div>
            </div>
        }
    </div>

</div>

GestionDeportiva/Views/Eventos/Search.cshtml
@model List<GestionDeportiva.Models.Eventos>

@{
    ViewBag.Title = "Busqueda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Resultados de la Busqueda: @ViewBag.ValorBuscado</h2>

@if (Model.Count > 0)
{
    <div class="d-flex gap-3 p-3 flex-wrap justify-content-center">
        @foreach (var item in Model)
        {
            <div class="card m-1" style="width: 18rem;">
                <img src="@($"Data:image/PNG;base64,{Convert.ToBase64String(item.Imagen)}")" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@item.Nombre</h5>
                    <p class="card-text">@item.Descripcion.</p>
                    <p class="card-text">Fecha: @item.Fecha.Value.ToLongDateString() - @item.Fecha.Value.ToShortTimeString();</p>
                    @Html.ActionLink("Ver información", "Details", new { id = item.EventoId }, new { @class = "btn btn-sm btn-outline-primary" })
                </div>
            </div>
        }
    </div>
}
else
{
<div>
    <p class="text-danger">
        No hay coincidencias con el valor sugerido.
    </p>
</div>
    
}